site_name: UgPhone Help Center
exclude_docs: |
  CHANGELOG.md
  PROJECT_STATUS.md
theme:
  name: material

nav:
  - Rate Table: rates-en.md
  - Upgrade Calculator: calculator.md
  - Game Search Tool: game-search.md
  - Game Support: support.md
